### ISSUE TITLE
ls_postgres.c

### ISSUE THREAD

**Issue by emayo** [keplerproject/luasql#42]
I'm able to build Lua and LuaSQL with Embarcadero C++ Builder Rad Studio but had to make the following code modification to ls_postgres.c

The offending line, because len is not constant is not legal code.  I imagine some compilers just deal with it.
char to[len * sizeof(char) * 2 +1];

/*
** Escapes a string for use within an SQL statement.
** Returns a string with the escaped string.
*/
static int conn_escape (lua_State *L)
{
  int rval = 0;
  conn_data *conn = getconnection (L);
  size_t len;
  const char *from = luaL_checklstring (L, 2, &len);
  const size_t tolen = len * sizeof(char) * 2 + 1;
  char *to = malloc(tolen);
  int error;
  len = PQescapeStringConn (conn->pg_conn, to, from, len, &error);
  if (error == 0)
  { /* success ! */
    lua_pushlstring (L, to, len);
    rval = 1;
  }
  else
    rval = luasql_failmsg (L, "cannot escape string. PostgreSQL: ", PQerrorMessage (conn->pg_conn));

  free(to);
  return(rval);
}

**Comment by echiesse** [comment]
Can't believe this. Check this out: https://github.com/keplerproject/luasql/pull/13 
(23 Nov 2013)

**Comment by hishamhm** [comment]
@echiesse, LuaSQL suffers from the lack of active maintainers. I'm _not_ one of them, but since I have access to the repo I receive the notification emails, and I try to help out a bit when I can. 

Back in 2013, I saw your PR, gave it a quick look, noted that the indentation was incorrect, posted a message and forgot about it. You never fixed the indentation in the PR or sent a reply, so the PR just sat there. If you had, I would have probably seen it and pressed the "Merge" button.

**Comment by echiesse** [comment]
Done.

I know you're not the responsible for this issue. In fact, I think you do a nice job maintaining LuaRocks. And in the middle of the discution about "out of memory safety" I completely lost your comment. The maintainer at that time told he would analyse the issue in order to come up with a better approach in case of an exception. And I then mostly lost track of it.

Well, it was just spaces vs tabs.

**Comment by tomasguisasola** [comment]
Hi

Sorry but that's not the correct way to implement, since Lua can 
longjump after
malloc and before free, and you get a memory leak.

I'll correct that this weekend.

Regards,
Tomás

**Comment by tomasguisasola** [comment]
The issue was corrected here in the repo and a new version (2.3.1) was uploaded to LuaRocks. Check that, please.
