### ISSUE TITLE
Cannot install luasql-odbc(No results matching query were found)

### ISSUE THREAD

**Issue by sylfree9999** [keplerproject/luasql#83]
Hi,
I'm quite new to lua and linux. So if anything silly, please bear with me.
What I'm trying to do is to connect a remote ms sql server from centos 7.
I tried to install luasql-odbc.
So I installed lua and luarocks, unixODBC and msodbcsql(don't know if this helps).
But when I tried 
` luarocks install luasql-odbc,`
it says _No results matching query were found_.
Can anyone helps how I can install the luasql-odbc?
![20171030160518](https://user-images.githubusercontent.com/15099465/32160325-39b54714-bd8c-11e7-9a88-16b4b875c70a.png)

PS. I have also tried using 
`luarocks install --server=http://luarocks.org/dev luasql-odbc`

But with the error:
_cp: cannot stat ‘src/*.so’: No such file or directory_
![20171030160518](https://user-images.githubusercontent.com/15099465/32161494-b29bc154-bd90-11e7-9b59-0266d5e78fd7.png)

**Comment by AnkurThakur** [comment]
I know it is quite late. But still, I would like to post the solution here for anyone facing the same problem. Installed it manually as:

1. Cloned this LuaSQL using git to somewhere on the server.
2. Inside the source code, modified the **config** file provided and changed `PREFIX ?= /usr` and `LUA_SYS_VER ?= 5.1` according to my installation.
**Example:** I used `PREFIX ?= /usr/local` instead of the default.
3. Inside the **Makefile**, you'll see that you can build the **odbc.so** with `make odbc` command and it will save **odbc.so** file inside **src**.
4. At last, running `make install` will copy this **odbc.so** file to required directories.

Now you can test it inside lua by running `require "luasql.odbc"`

**Comment by tomasguisasola** [comment]
It seems the problem could be solved with adequate parameters to make, don't you agree?
